Repository kubernetes/kube-deploy, pull requests merged in 2018-04, with the labels that each got.

#658 Introducing MachineDeployment types.
  cluster-api/pkg/apis/cluster/common/consts.go
  cluster-api/pkg/apis/cluster/v1alpha1/machinedeployment_types.go
  cluster-api/pkg/apis/cluster/v1alpha1/zz_generated.api.register.go
  cluster-api/pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
  cluster-api/pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  cluster-api/pkg/apis/cluster/zz_generated.api.register.go
  cluster-api/pkg/apis/cluster/zz_generated.deepcopy.go
  cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/cluster_client.go
  cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/fake_cluster_client.go
  cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/fake_machinedeployment.go
  cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/generated_expansion.go
  cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/machinedeployment.go
  cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/interface.go
  cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/machinedeployment.go
  cluster-api/pkg/client/informers_generated/externalversions/generic.go
  cluster-api/pkg/client/listers_generated/cluster/v1alpha1/expansion_generated.go
  cluster-api/pkg/client/listers_generated/cluster/v1alpha1/machinedeployment.go
  cluster-api/pkg/openapi/openapi_generated.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#665 Include step in prereq to login.
  cluster-api/gcp-deployer/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#668 Add make rules for correcting permissions on GCR public images
  cluster-api/cloud/google/cmd/gce-machine-controller/Makefile
  cluster-api/cmd/apiserver/Makefile
  cluster-api/cmd/controller-manager/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#671 Remove Machine UID checking
  cluster-api/cloud/google/instancestatus.go
  cluster-api/cloud/google/machineactuator.go
  cluster-api/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#673 Bump machine controller image to take in PR 671
  cluster-api/cloud/google/cmd/gce-machine-controller/Makefile
  cluster-api/cloud/google/pods.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#682 Bump for #679
  cluster-api/cloud/google/cmd/gce-machine-controller/Makefile
  cluster-api/cloud/google/pods.go
  cluster-api/cmd/apiserver/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#684 Add "reviewers" list to OWNERS for blunderbuss to request review
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#685 Remove extra tab from CONTRIBUTING.md
  cluster-api/gcp-deployer/CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#646 AWS 1.9 image
  imagebuilder/aws-1.9-jessie.yaml
  imagebuilder/aws-1.9-stretch.yaml
  imagebuilder/templates/1.9-jessie.yml
  imagebuilder/templates/1.9-stretch.yml
Labels: approved, cncf-cla: yes, size/L
