Repository kubernetes/kube-deploy, pull requests merged in 2018-03, with the labels that each got.

#582 Start using apimachinery backoff for retries
  cluster-api-gcp/deploy/deploy_helper.go
  cluster-api-gcp/util/retry.go
  cluster-api/util/util.go
  ext-apiserver/gcp-deployer/deploy/deploy_helper.go
  ext-apiserver/util/retry.go
  ext-apiserver/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#624 Make OS image configurable
  ext-apiserver/cloud/google/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#630 Remove apimachinery/wait dep from deploy_helper
  ext-apiserver/gcp-deployer/deploy/deploy_helper.go
  ext-apiserver/util/retry.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#641 Updating owners aliases to reflect changes to sig leadership and the github teams
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#620 initial implementation of machineset controller
  ext-apiserver/pkg/apis/cluster/v1alpha1/machineset_types.go
  ext-apiserver/pkg/apis/cluster/v1alpha1/machineset_types_test.go
  ext-apiserver/pkg/apis/cluster/v1alpha1/v1alpha1_suite_test.go
  ext-apiserver/pkg/controller/machineset/controller.go
  ext-apiserver/pkg/controller/machineset/controller_test.go
  ext-apiserver/pkg/controller/machineset/reconcile_test.go
  ext-apiserver/sample/machineset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#644 Change DNSDomain to service domain
  ext-apiserver/cloud/google/machineactuator.go
  ext-apiserver/cloud/google/templates.go
  ext-apiserver/gcp-deployer/cluster.yaml
  ext-apiserver/pkg/apis/cluster/v1alpha1/cluster_types.go
  ext-apiserver/pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
  ext-apiserver/pkg/apis/cluster/zz_generated.api.register.go
  ext-apiserver/pkg/openapi/openapi_generated.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#640 Add boostrap guidance to contributing guide
  ext-apiserver/CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#651 Delete the client side machineset, now that we have MachineSet in the API
  ext-apiserver/.gitignore
  ext-apiserver/README.md
  ext-apiserver/gcp-deployer/README.md
  ext-apiserver/tools/machineset/.gitignore
  ext-apiserver/tools/machineset/README.md
  ext-apiserver/tools/machineset/get.go
  ext-apiserver/tools/machineset/main.go
  ext-apiserver/tools/machineset/scale.go
  ext-apiserver/tools/machineset/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#652 Update the machine controller image to pick up #644
  ext-apiserver/cloud/google/pods.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#656 Change type of providerConfig to runtime.RawExtension
  cluster-api/cloud/google/machineactuator.go
  cluster-api/cloud/google/pods.go
  cluster-api/gcp-deployer/machines.yaml.template
  cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
  cluster-api/pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
  cluster-api/pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  cluster-api/pkg/apis/cluster/zz_generated.api.register.go
  cluster-api/pkg/apis/cluster/zz_generated.deepcopy.go
  cluster-api/pkg/controller/machineset/reconcile_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#657 Update the sample machineset config with the new provider config
  cluster-api/sample/machineset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#648 Add Validation for cluster resource type in apiserver
  cluster-api/cloud/google/machineactuator.go
  cluster-api/pkg/apis/cluster/v1alpha1/cluster_types.go
  cluster-api/pkg/apis/cluster/v1alpha1/cluster_types_test.go
  cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
  cluster-api/pkg/apis/cluster/v1alpha1/testutil/testutil.go
  cluster-api/pkg/apis/cluster/v1alpha1/v1alpha1_suite_test.go
  cluster-api/pkg/controller/cluster/controller_test.go
  cluster-api/pkg/controller/machine/controller_test.go
  cluster-api/pkg/controller/machineset/controller_test.go
  cluster-api/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#649 Break the machine controller's dependency on Google Actuator
  cluster-api/cloud/actuators.go
  cluster-api/cloud/azure/machineactuator.go
  cluster-api/cloud/google/cmd/gce-machine-controller/.gitignore
  cluster-api/cloud/google/cmd/gce-machine-controller/Dockerfile
  cluster-api/cloud/google/cmd/gce-machine-controller/Makefile
  cluster-api/cloud/google/cmd/gce-machine-controller/main.go
  cluster-api/cloud/google/config/configtemplate.go
  cluster-api/cloud/google/pods.go
  cluster-api/cmd/apiserver/.gitignore
  cluster-api/cmd/apiserver/Dockerfile
  cluster-api/cmd/apiserver/Makefile
  cluster-api/cmd/controller-manager/.gitignore
  cluster-api/cmd/controller-manager/Dockerfile
  cluster-api/cmd/controller-manager/Makefile
  cluster-api/cmd/controller-manager/main.go
  cluster-api/gcp-deployer/deploy/deploy.go
  cluster-api/gcp-deployer/deploy/machinedeployer.go
  cluster-api/pkg/controller/config/configuration.go
  cluster-api/pkg/controller/machine/actuator.go
  cluster-api/pkg/controller/machine/controller.go
  cluster-api/pkg/controller/machine/machine_suite_test.go
  cluster-api/pkg/controller/machine/zz_generated.api.register.go
  cluster-api/pkg/controller/machineset/machineset_suite_test.go
  cluster-api/pkg/controller/zz_generated.api.register.go
Labels: approved, cncf-cla: yes, lgtm, size/XL
