Repository kubernetes/kube-deploy, pull requests merged in 2018-02, with the labels that each got.

#590 Remove newline from test script
  scripts/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#586 Firewall creation should be after gcloud was installed
  cluster-api-gcp/CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#572 Plumbing cluster-api-gcp to use new API type
  ext-apiserver/cloud/google/config/apiserver.yaml
  ext-apiserver/cloud/google/machineactuator.go
  ext-apiserver/cloud/google/pods.go
  ext-apiserver/cloud/google/pods/machine-controller.yaml
  ext-apiserver/cloud/google/serviceaccount.go
  ext-apiserver/cloud/google/ssh.go
  ext-apiserver/gcp-deployer/cluster.yaml
  ext-apiserver/gcp-deployer/cmd/add.go
  ext-apiserver/gcp-deployer/cmd/create.go
  ext-apiserver/gcp-deployer/cmd/delete.go
  ext-apiserver/gcp-deployer/cmd/root.go
  ext-apiserver/gcp-deployer/deploy/deploy.go
  ext-apiserver/gcp-deployer/deploy/deploy_helper.go
  ext-apiserver/gcp-deployer/deploy/machinedeployer.go
  ext-apiserver/gcp-deployer/machines.yaml
  ext-apiserver/gcp-deployer/main.go
  ext-apiserver/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#581 Implement finalizer support for machine resource
  ext-apiserver/cloud/google/machineactuator.go
  ext-apiserver/gcp-deployer/deploy/deploy_helper.go
  ext-apiserver/pkg/apis/cluster/v1alpha1/machine_types.go
  ext-apiserver/pkg/controller/config/configuration.go
  ext-apiserver/pkg/controller/machine/controller.go
  ext-apiserver/util/util.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/L

#597 Fix the machine controller tests
  ext-apiserver/pkg/controller/machine/controller_test.go
  ext-apiserver/pkg/controller/machine/machine_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#598 Clear finalizer in test so it can actually delete
  ext-apiserver/pkg/apis/cluster/v1alpha1/machine_types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#588 Implement node watcher functionality in new controller
  ext-apiserver/pkg/controller/machine/controller.go
  ext-apiserver/pkg/controller/machine/node.go
  ext-apiserver/pkg/controller/sharedinformers/informers.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#501 add MachineSet type
  cluster-api/api/cluster/v1alpha1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#577 Fixes #424, merge new kube config with existing config file
  cluster-api-gcp/deploy/deploy_helper.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#607 Update client dependency to fix a race condition
  ext-apiserver/Gopkg.lock
  ext-apiserver/vendor/k8s.io/client-go/Godeps/Godeps.json
  ext-apiserver/vendor/k8s.io/client-go/tools/cache/shared_informer.go
  ext-apiserver/vendor/k8s.io/client-go/tools/cache/shared_informer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#610 Switch to listing clusters on demand instead of caching them
  ext-apiserver/pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#603 Add Cluster API architecture diagram to README.md
  cluster-api/README.md
  cluster-api/architecture.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#605 bake deploy template into gcp-deployer
  ext-apiserver/cloud/google/config/configtemplate.go
  ext-apiserver/cloud/google/pods.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#615 updates generated code for MachineSet
  cluster-api/api/cluster/v1alpha1/types.go
  cluster-api/api/cluster/v1alpha1/zz_generated.deepcopy.go
  cluster-api/client/clientset/versioned/typed/cluster/v1alpha1/cluster_client.go
  cluster-api/client/clientset/versioned/typed/cluster/v1alpha1/fake/fake_cluster_client.go
  cluster-api/client/clientset/versioned/typed/cluster/v1alpha1/fake/fake_machineset.go
  cluster-api/client/clientset/versioned/typed/cluster/v1alpha1/generated_expansion.go
  cluster-api/client/clientset/versioned/typed/cluster/v1alpha1/machineset.go
  cluster-api/client/informers/externalversions/cluster/v1alpha1/interface.go
  cluster-api/client/informers/externalversions/cluster/v1alpha1/machineset.go
  cluster-api/client/informers/externalversions/generic.go
  cluster-api/client/listers/cluster/v1alpha1/expansion_generated.go
  cluster-api/client/listers/cluster/v1alpha1/machineset.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#614 Cherry-pick the MachineAPI chanage from cluster-api to ext-apiserver
  ext-apiserver/docs/proposals/machine-api-proposal.md
  ext-apiserver/pkg/apis/cluster/common/consts.go
  ext-apiserver/pkg/apis/cluster/v1alpha1/machine_types.go
  ext-apiserver/pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
  ext-apiserver/pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  ext-apiserver/pkg/apis/cluster/zz_generated.api.register.go
  ext-apiserver/pkg/apis/cluster/zz_generated.deepcopy.go
  ext-apiserver/pkg/openapi/openapi_generated.go
  ext-apiserver/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#606 Use openssl to generate certs
  ext-apiserver/cloud/google/pods.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#617 Port the tools to use new API.
  ext-apiserver/tools/README.md
  ext-apiserver/tools/machineset/.gitignore
  ext-apiserver/tools/machineset/README.md
  ext-apiserver/tools/machineset/get.go
  ext-apiserver/tools/machineset/main.go
  ext-apiserver/tools/machineset/scale.go
  ext-apiserver/tools/machineset/util.go
  ext-apiserver/tools/repair/.gitignore
  ext-apiserver/tools/repair/README.md
  ext-apiserver/tools/repair/cmd/root.go
  ext-apiserver/tools/repair/main.go
  ext-apiserver/tools/repair/util/repair.go
  ext-apiserver/tools/upgrader/.gitignore
  ext-apiserver/tools/upgrader/README.md
  ext-apiserver/tools/upgrader/cmd/root.go
  ext-apiserver/tools/upgrader/main.go
  ext-apiserver/tools/upgrader/util/upgrade.go
  ext-apiserver/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#622 Convert ginko tests to standard testing framework
  ext-apiserver/pkg/apis/cluster/v1alpha1/BUILD
  ext-apiserver/pkg/apis/cluster/v1alpha1/cluster_types_test.go
  ext-apiserver/pkg/apis/cluster/v1alpha1/machine_types_test.go
  ext-apiserver/pkg/apis/cluster/v1alpha1/v1alpha1_suite_test.go
  ext-apiserver/pkg/controller/cluster/BUILD
  ext-apiserver/pkg/controller/cluster/cluster_suite_test.go
  ext-apiserver/pkg/controller/cluster/controller_test.go
  ext-apiserver/pkg/controller/machine/BUILD
  ext-apiserver/pkg/controller/machine/controller_test.go
  ext-apiserver/pkg/controller/machine/machine_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#599 #571 generate random name, if generateName field set in spec
  cluster-api-gcp/deploy/deploy_helper.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#618 Copy the documentation over to the new location.
  ext-apiserver/.gitignore
  ext-apiserver/CONTRIBUTING.md
  ext-apiserver/README.md
  ext-apiserver/architecture.png
  ext-apiserver/gcp-deployer/CONTRIBUTING.md
  ext-apiserver/gcp-deployer/README.md
  ext-apiserver/gcp-deployer/generate-yaml.sh
  ext-apiserver/gcp-deployer/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/L
