Repository kubernetes/kube-deploy, pull requests merged in 2019-05, with the labels that each got.

#710 Add acpi-support to stretch images
  imagebuilder/templates/1.10-stretch.yml
  imagebuilder/templates/1.11-stretch.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#717 Set NVME Timeout to 255 istead of default 30. Per https://docs.aws.am…
  imagebuilder/templates/1.10-stretch.yml
  imagebuilder/templates/1.11-stretch.yml
  imagebuilder/templates/1.8-stretch.yml
  imagebuilder/templates/1.9-stretch.yml
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/XS

#711 don't passthru AWS creds when IAM role specified
  imagebuilder/pkg/imagebuilder/aws.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#725 Using go.k8s.io for pointing to OWNERS docs
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#727 Create image optimized for k8s 1.12
  imagebuilder/aws-1.12-stretch.yaml
  imagebuilder/templates/1.12-stretch.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#726 Ensure we have deleted all our SSH keys
  imagebuilder/templates/1.10-jessie.yml
  imagebuilder/templates/1.10-stretch.yml
  imagebuilder/templates/1.11-jessie.yml
  imagebuilder/templates/1.11-stretch.yml
  imagebuilder/templates/1.8-jessie.yml
  imagebuilder/templates/1.8-stretch.yml
  imagebuilder/templates/1.9-jessie.yml
  imagebuilder/templates/1.9-stretch.yml
Labels: approved, cncf-cla: yes, lgtm, size/M
